title: nwienert
url: http://natewienert.com
name: Nate Wienert
tagline: Not so subtle
twitter: natebirdman
github: http://github.com/natew
email: natewienert@gmail.com
google_analytics_id: UA-23975642-4
login: nwienert
password: fluf499